# Generated by Django 2.2 on 2019-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('id_card', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
