# Generated by Django 2.2 on 2019-04-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=1000)),
                ('_type', models.IntegerField()),
                ('audio', models.FileField(upload_to='')),
                ('page', models.CharField(max_length=10000)),
            ],
        ),
    ]
