# Generated by Django 2.2 on 2019-04-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.CharField(max_length=1000),
        ),
    ]
