# Generated by Django 2.2 on 2019-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0003_auto_20190408_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='audio',
            field=models.CharField(max_length=1000),
        ),
    ]
