# Generated by Django 2.2 on 2019-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0004_auto_20190408_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('article_id', models.IntegerField(max_length=130)),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('wx_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='top_view',
            field=models.IntegerField(default=0),
        ),
    ]
