# Generated by Django 2.2 on 2019-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_backend', '0005_auto_20190408_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number_of_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
